version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/project/
    ports:
    - 8081:80
  php:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
    - ./:/var/www/project/
#    environment:
#      - APP_ENV=prod
#      - APP_DEBUG=false

  redis:
    restart: unless-stopped
    image: redis
    volumes:
      - ./redis-data:/data
