# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    podcasts_urls:
        muzica-de-pus-pe-ganduri: "https://www.guerrillaradio.ro/emisiuni/muzica-de-pus-pe-ganduri/"
        muzica-despre-cine-suntem: "https://www.guerrillaradio.ro/emisiuni/muzica-despre-cine-suntem/"
        garana-jazz: "https://www.guerrillaradio.ro/emisiuni/garana-jazz/"
        guerrilive: "https://www.guerrillaradio.ro/emisiuni/guerrilive/"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            array $podcastsUrls: "%podcasts_urls%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
